--------------------------------------------------------
--  DDL for Table T_BREVLAGER_HISTORIKK
--------------------------------------------------------

CREATE TABLE T_BREVLAGER_HISTORIKK
(	BREVLAGER_HISTORIK_ID NUMBER(19,0) NOT NULL,
     BREVREFERANSE VARCHAR2(32 CHAR) NOT NULL,
     STATUS VARCHAR2(8 CHAR) NOT NULL,
     TIMESTAMP TIMESTAMP (6) NOT NULL,
     BRUKERID VARCHAR2(18 CHAR),
     SYSTEMID VARCHAR2(4 CHAR) NOT NULL,
     BREVDATA BLOB NOT NULL,
     CONTENTTYPE VARCHAR2(64 CHAR),
     VASKET CHAR(1 CHAR) NOT NULL,
	PARTKEY NUMBER(38,0),
	DB2_GENERATED_ROWID_FOR_LOBS RAW(40) NOT NULL,
    CONSTRAINT IBREVLAGERU PRIMARY KEY (BREVLAGER_HISTORIK_ID)
);

--------------------------------------------------------
--  DDL for Table T_BREVLAGER_X
--------------------------------------------------------

CREATE TABLE T_BREVLAGER_X
(	BLOBID RAW(40) NOT NULL auto_increment,
     BREVREFERANSE VARCHAR2(32 CHAR) NOT NULL,
     STATUS VARCHAR2(8 CHAR) NOT NULL,
     TIMESTAMP TIMESTAMP (6) NOT NULL,
     BRUKERID VARCHAR2(18 CHAR),
     SYSTEMID VARCHAR2(4 CHAR) NOT NULL,
     BREVDATA BLOB NOT NULL,
     CONTENTTYPE VARCHAR2(64 CHAR),
     VASKET CHAR(1 CHAR) NOT NULL,
	PARTKEY NUMBER(38,0) NOT NULL
   );
CREATE UNIQUE INDEX XPKT_BREVLAGER_X ON T_BREVLAGER_X (BREVREFERANSE, SYSTEMID);
ALTER TABLE T_BREVLAGER_X ADD CONSTRAINT XPKT_BREVLAGER_X PRIMARY KEY (BREVREFERANSE, SYSTEMID);
--------------------------------------------------------
--  DDL for Table T_BREVSTATUS
--------------------------------------------------------

CREATE TABLE T_BREVSTATUS
(	BREVREFERANSE VARCHAR2(32 CHAR) NOT NULL,
     RETURKOE VARCHAR2(256 CHAR) NOT NULL,
     BESTILLERBRUKERID VARCHAR2(100 CHAR),
     BREVMAL VARCHAR2(255 CHAR) NOT NULL,
     TIMESTAMP TIMESTAMP (6) NOT NULL,
     SYSTEMID VARCHAR2(4 CHAR) NOT NULL,
     STATUS VARCHAR2(8 CHAR) NOT NULL,
     FORMAT VARCHAR2(32 CHAR),
     SKRIVERTYPE VARCHAR2(16 CHAR),
     SKRIVER VARCHAR2(32 CHAR),
     ARKIVER VARCHAR2(3 CHAR),
     SKUFF VARCHAR2(32 CHAR)
);
CREATE UNIQUE INDEX XPKT_BREVSTATUS ON T_BREVSTATUS (BREVREFERANSE, SYSTEMID);
  ALTER TABLE T_BREVSTATUS ADD CONSTRAINT XPKT_BREVSTATUS PRIMARY KEY (BREVREFERANSE, SYSTEMID);
--------------------------------------------------------
--  DDL for Table T_BREVSYSTILGANG
--------------------------------------------------------

CREATE TABLE T_BREVSYSTILGANG
(	SYSTEMID VARCHAR2(4 CHAR) NOT NULL,
     SYSTEMPASSORD VARCHAR2(32 CHAR) NOT NULL,
     ELDOK_ID VARCHAR2(20 CHAR),
     ELDOK_PWD VARCHAR2(20 CHAR)
);
CREATE UNIQUE INDEX XPKT_BREVSYSTILGAN ON T_BREVSYSTILGANG (SYSTEMID);
  ALTER TABLE T_BREVSYSTILGANG ADD CONSTRAINT XPKT_BREVSYSTILGAN PRIMARY KEY (SYSTEMID);
--------------------------------------------------------
--  DDL for Table T_BREVTILGANG
--------------------------------------------------------


CREATE TABLE T_BREVTILGANG
(	BREVREFERANSE VARCHAR2(32 CHAR),
     TOKEN VARCHAR2(64 CHAR),
     TIMESTAMP TIMESTAMP (6),
     SYSTEMID VARCHAR2(4 CHAR),
     ID NUMBER(19,0) NOT NULL
);
--------------------------------------------------------
--  DDL for Table T_BREVSTATISTIKK
--------------------------------------------------------
CREATE TABLE T_BREVSTATISIKK
(	ID NUMBER(19,0) NOT NULL,
     FREKVENS VARCHAR2(18 CHAR) NOT NULL,
     SQL VARCHAR2(2000 CHAR) NOT NULL,
     MOTTAKER VARCHAR2(1024 CHAR) NOT NULL,
     CONSTRAINT XPKT_BREVSTATISIKK PRIMARY KEY (ID)
);
CREATE TABLE T_KONVBREV
(	SYSTEMID VARCHAR2(4 CHAR) NOT NULL,
     BREVREFERANSE VARCHAR2(32 CHAR) NOT NULL,
     DOKID VARCHAR2(32 CHAR) NOT NULL,
     VERID VARCHAR2(10 CHAR),
     VARIANT CHAR(1 CHAR),
	 CONSTRAINT XPKT_KONVBREV PRIMARY KEY (BREVREFERANSE, SYSTEMID)
);