ALTER TABLE T_BREVLAGER_HISTORIKK MODIFY DB2_GENERATED_ROWID_FOR_LOBS RAW(40) DEFAULT '42';
ALTER TABLE T_BREVLAGER_X MODIFY VASKET CHAR(1 CHAR) DEFAULT '0';
ALTER TABLE T_BREVLAGER_X MODIFY PARTKEY NUMBER(38,0) DEFAULT '42';
ALTER TABLE T_BREVLAGER_HISTORIKK MODIFY VASKET CHAR(1 CHAR) DEFAULT '0';
