DROP SEQUENCE BREVLAGER_HISTORIKK_SEQ;
CREATE SEQUENCE BREVLAGER_HISTORIKK_SEQ START WITH 17000000 INCREMENT BY 1;
DROP SEQUENCE BREVTILGANG_SEQ;
CREATE SEQUENCE BREVTILGANG_SEQ START WITH 80008000 INCREMENT BY 1;