CREATE TABLE BREVSTATUS
(
    BREVREFERANSE     VARCHAR2(32 CHAR) NOT NULL,
    RETURKOE          VARCHAR2(100 CHAR) NOT NULL,
    BESTILLERBRUKERID VARCHAR2(18 CHAR),
    BREVMAL           VARCHAR2(255 CHAR) NOT NULL,
    SYSTEMID          VARCHAR2(4 CHAR) NOT NULL,
    STATUS            VARCHAR2(8 CHAR) NOT NULL,
    FORMAT            VARCHAR2(32 CHAR) NOT NULL,
    SKRIVERTYPE       VARCHAR2(16 CHAR),
    SKRIVER           VARCHAR2(32 CHAR),
    ARKIVER           VARCHAR2(3 CHAR),
    SKUFF             VARCHAR2(32 CHAR),
    KNAPPSTATUS       INTEGER,
    DATO_ENDRET DATE NOT NULL,
    ENDRET_AV VARCHAR2(100 CHAR) NOT NULL,
    DATO_OPPRETTET DATE NOT NULL,
    OPPRETTET_AV VARCHAR2(100 CHAR) NOT NULL
);

CREATE TABLE BREVSYSTILGANG
(
    SYSTEMID      VARCHAR2(4 CHAR) NOT NULL,
    SYSTEMPASSORD VARCHAR2(32 CHAR) NOT NULL,
    ELDOK_ID      VARCHAR2(20 CHAR),
    ELDOK_PWD     VARCHAR2(20 CHAR)
);

CREATE TABLE BREVTILGANG
(
    ID        NUMBER(19,0) PRIMARY KEY,
    BREVREFERANSE   VARCHAR2(32 CHAR),
    TOKEN     VARCHAR2(64 CHAR),
    SYSTEMID  VARCHAR2(4 CHAR),
    DATO_ENDRET DATE NOT NULL,
    ENDRET_AV VARCHAR2(100 CHAR) NOT NULL,
    DATO_OPPRETTET DATE NOT NULL,
    OPPRETTET_AV VARCHAR2(100 CHAR) NOT NULL
);

CREATE TABLE BREVLAGER
(
    ID        NUMBER(19,0) PRIMARY KEY,
    BREVREFERANSE VARCHAR2(32 CHAR) NOT NULL,
    STATUS        VARCHAR2(8 CHAR) NOT NULL,
    BRUKERID      VARCHAR2(18 CHAR),
    SYSTEMID      VARCHAR2(4 CHAR) NOT NULL,
    BREVDATA      BLOB      NOT NULL,
    CONTENTTYPE   VARCHAR2(64 CHAR),
    VASKET        CHAR,
    PARTKEY       SMALLINT,
    DATO_ENDRET DATE NOT NULL,
    ENDRET_AV VARCHAR2(100 CHAR) NOT NULL,
    DATO_OPPRETTET DATE NOT NULL,
    OPPRETTET_AV VARCHAR2(100 CHAR) NOT NULL
);

CREATE SEQUENCE BREVLAGER_HISTORIKK_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE BREVLAGER_HISTORIKK
(
    BREVLAGER_HISTORIK_ID INTEGER   NOT NULL,
    BREVREFERANSE         VARCHAR2(32 CHAR) NOT NULL,
    STATUS                VARCHAR2(8 CHAR) NOT NULL,
    BRUKERID              VARCHAR2(18 CHAR),
    SYSTEMID              VARCHAR2(4 CHAR) NOT NULL,
    BREVDATA              BLOB      NOT NULL,
    CONTENTTYPE           VARCHAR2(64 CHAR),
    VASKET                CHAR      NOT NULL,
    PARTKEY               SMALLINT,
    DATO_ENDRET DATE NOT NULL,
    ENDRET_AV VARCHAR2(100 CHAR) NOT NULL,
    DATO_OPPRETTET DATE NOT NULL,
    OPPRETTET_AV VARCHAR2(100 CHAR) NOT NULL
);

