# database
spring.datasource.driver-class-name=oracle.jdbc.pool.OracleDataSource
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.generate_statistics=false