<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.1</version>
	</parent>

	<groupId>no.nav.brevserver</groupId>
	<artifactId>brevserver</artifactId>
	<packaging>pom</packaging>
	<version>1.0-SNAPSHOT</version>

	<modules>
		<module>core</module>
		<module>fagarkiv-consumer</module>
		<module>service</module>
		<module>bestillBrev</module>
		<module>arkiverBrev</module>
		<module>app</module>
	</modules>

	<properties>
		<java.version>17</java.version>

		<!-- Interne NAV-dependencies -->
		<dok-legacy-tjenestespesifikasjoner.version>29-af3d66d</dok-legacy-tjenestespesifikasjoner.version>

<!--		<oracle.version>19.20.0.0</oracle.version>-->
		<camel.version>4.1.0</camel.version>
		<token-support.version>3.2.0</token-support.version>
		<ibm-mq.version>9.3.3.1</ibm-mq.version>
<!--		<activemq.version>5.18.2</activemq.version>-->
		<commons-io.version>2.15.1</commons-io.version>
		<dozer-spring-boot-starter.version>6.5.2</dozer-spring-boot-starter.version>
		<logstash-logback-encoder.version>7.3</logstash-logback-encoder.version>
		<jakarta.jws-api.version>1.1.1</jakarta.jws-api.version>

		<patrodyne-basicjaxb.version>2.1.1</patrodyne-basicjaxb.version>

		<bcprov-jdk15on.version>1.70</bcprov-jdk15on.version>
		<messaginghub.version>3.1.5</messaginghub.version>

		<!-- test -->
		<!-- Overstyrer Spring Boot sin versjon som gir flyway-feil - versjon 1.4.200 fungerer heller ikke for testene -->
		 <h2.version>1.4.199</h2.version>

		<!-- Plugins -->
		<maven-toolchains-plugin.version>3.1.0</maven-toolchains-plugin.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>no.nav.brevserver</groupId>
				<artifactId>service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.brevserver</groupId>
				<artifactId>fagarkiv-consumer</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.brevserver</groupId>
				<artifactId>core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.brevserver</groupId>
				<artifactId>bestillBrev</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.brevserver</groupId>
				<artifactId>arkiverBrev</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- NAV dependencies -->
			<dependency>
				<groupId>no.nav.tjenester.brevogarkiv</groupId>
				<artifactId>dokumentbehandling-tjenestespesifikasjon</artifactId>
				<version>${dok-legacy-tjenestespesifikasjoner.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.tjenester.brevogarkiv</groupId>
				<artifactId>loggmottak-tjenestespesifikasjon</artifactId>
				<version>${dok-legacy-tjenestespesifikasjoner.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.tjenester</groupId>
				<artifactId>nav-journal-tjenestespesifikasjon</artifactId>
				<version>${dok-legacy-tjenestespesifikasjoner.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.tjenester</groupId>
				<artifactId>nav-journalbehandling-tjenestespesifikasjon</artifactId>
				<version>${dok-legacy-tjenestespesifikasjoner.version}</version>
			</dependency>
			<!-- Kan fjernes når spring-ws-security sine avhengigheter har fått oppdatert bcprov-jdk15on	-->
			<dependency>
				<groupId>org.bouncycastle</groupId>
				<artifactId>bcprov-jdk15on</artifactId>
				<version>${bcprov-jdk15on.version}</version>
			</dependency>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>${commons-io.version}</version>
			</dependency>
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logstash-logback-encoder.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.dozermapper</groupId>
				<artifactId>dozer-spring-boot-starter</artifactId>
				<version>${dozer-spring-boot-starter.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.security</groupId>
				<artifactId>token-validation-spring</artifactId>
				<version>${token-support.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.camel</groupId>
				<artifactId>camel-bom</artifactId>
				<version>${camel.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.camel.springboot</groupId>
				<artifactId>camel-spring-boot-bom</artifactId>
				<version>${camel.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.ibm.mq</groupId>
				<artifactId>com.ibm.mq.jakarta.client</artifactId>
				<version>${ibm-mq.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.jws</groupId>
				<artifactId>jakarta.jws-api</artifactId>
				<version>${jakarta.jws-api.version}</version>
			</dependency>
			<dependency>
				<groupId>org.patrodyne.jvnet</groupId>
				<artifactId>hisrc-basicjaxb-runtime</artifactId>
				<version>${patrodyne-basicjaxb.version}</version>
			</dependency>
			<dependency>
				<groupId>org.messaginghub</groupId>
				<artifactId>pooled-jms</artifactId>
				<version>${messaginghub.version}</version>
			</dependency>


			<!-- Test -->
			<dependency>
				<groupId>no.nav.security</groupId>
				<artifactId>token-validation-spring-test</artifactId>
				<version>${token-support.version}</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>

		<!-- Logging -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>

		<!-- Test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>com.vaadin.external.google</groupId>
					<artifactId>android-json</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>artemis-jakarta-server</artifactId>
			<version>${artemis.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-toolchains-plugin</artifactId>
				<version>${maven-toolchains-plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>toolchain</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<toolchains>
						<jdk>
							<version>${java.version}</version>
							<vendor>openjdk</vendor>
						</jdk>
					</toolchains>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>