<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>brevserver</artifactId>
		<groupId>no.nav.brevserver</groupId>
		<version>10.2.1-SNAPSHOT</version>
	</parent>
	<artifactId>brevserver-server-business-ejb</artifactId>
	<name>${project.artifactId}</name>
	<version>10.2.1-SNAPSHOT</version>
	<packaging>ejb</packaging>

	<dependencies>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-config</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-consumer-joark-ejb</artifactId>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-server-common-java</artifactId>
		</dependency>
		<dependency>
			<groupId>xerces</groupId>
			<artifactId>xercesImpl</artifactId>
		</dependency>
		<dependency>
			<groupId>aspose</groupId>
			<artifactId>aspose-words-jdk15</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>jsr250-api</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.jms</groupId>
			<artifactId>jms</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>

		<!-- Test dependencies -->
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-config</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-consumer-joark-ejb</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-server-common-java</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>simple-jndi</groupId>
			<artifactId>simple-jndi</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-dbutils</groupId>
			<artifactId>commons-dbutils</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mysema.querydsl</groupId>
			<artifactId>querydsl-sql</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-dbcp</groupId>
			<artifactId>commons-dbcp</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc8</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ucp</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-commons</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-core</artifactId>
			<version>10.2.1-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-repository</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>sql-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.h2database</groupId>
						<artifactId>h2</artifactId>
						<version>${h2.version}</version>
						<scope>compile</scope>
					</dependency>
				</dependencies>
				<configuration>
					<driver>org.h2.Driver</driver>
					<url>jdbc:h2:${project.basedir}/target/TEST_BREV_DDL</url>
					<username>sa</username>
					<srcFiles>
						<srcFile>src/test/resources/create-database.sql</srcFile>
					</srcFiles>
					<onError>continue</onError>
				</configuration>
				<executions>
					<execution>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>execute</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.mysema.querydsl</groupId>
				<artifactId>querydsl-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>test-export</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<jdbcDriver>org.h2.Driver</jdbcDriver>
					<jdbcUrl>jdbc:h2:${project.basedir}/target/TEST_BREV_DDL</jdbcUrl>
					<jdbcUser>sa</jdbcUser>
					<exportBeans>true</exportBeans>
					<packageName>no.nav.brevserver.querydsl</packageName>
					<targetFolder>${project.basedir}/target/generated-test-sources/java</targetFolder>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.h2database</groupId>
						<artifactId>h2</artifactId>
						<version>${h2.version}</version>
					</dependency>
					<dependency>
						<groupId>org.slf4j</groupId>
						<artifactId>slf4j-nop</artifactId>
						<version>${slf4j.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>add-test-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${project.build.directory}/generated-test-sources/java</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
					<archive>
						<manifest>
							<classpathPrefix>lib/</classpathPrefix>
							<addClasspath>true</addClasspath>
						</manifest>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>