
# XML parsing
ArkiverBrevCommand.headerLengde=350
ArkiverBrevCommand.headerlengde.antTegnIStartAvMelding=0

# Aspose PDF conversion settings
aspose.license.location=aspose/license/Aspose.Words.lic
aspose.fonts.location=aspose/fonts

# BrevAdmin
BrevAdmin.dokid=103205000930
BrevAdmin.utvidetAdministrasjon=true
Menu.dokURL=http://confluence.adeo.no/display/BAForv/
Menu.zipURL=http://confluence.adeo.no/download/attachments/32145413/xdocs.zip
SearchService.lookinlogfiles=true
SearchService.logdir=/var/log/apps/brevserver/app
SearchService.logfile=brevserver.log
SearchService.doValidation=true
