<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>brevserver</artifactId>
		<groupId>no.nav.brevserver</groupId>
		<version>10.2.1-SNAPSHOT</version>
	</parent>
	<artifactId>brevserver-provider-ws</artifactId>
	<packaging>war</packaging>
	<version>10.2.1-SNAPSHOT</version>

	<dependencies>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-server-business-ejb</artifactId>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-server-common-java</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester.brevogarkiv</groupId>
			<artifactId>dokumentbehandling-tjenestespesifikasjon</artifactId>
			<classifier>jaxws</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester.brevogarkiv</groupId>
			<artifactId>loggmottak-tjenestespesifikasjon</artifactId>
			<classifier>jaxws</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-klient-applet</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-consumer-joark-ejb</artifactId>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
		</dependency>
		<dependency>
			<groupId>net.sf.dozer</groupId>
			<artifactId>dozer</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet.jsp</groupId>
			<artifactId>jsp-api</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.jms</groupId>
			<artifactId>jms</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sun.istack</groupId>
			<artifactId>istack-commons-runtime</artifactId>
		</dependency>

		<!-- Test dependencies -->
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-config</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-server-business-ejb</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-consumer-joark-ejb</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>simple-jndi</groupId>
			<artifactId>simple-jndi</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-dbutils</groupId>
			<artifactId>commons-dbutils</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mysema.querydsl</groupId>
			<artifactId>querydsl-sql</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>no.nav.brevserver</groupId>
									<artifactId>brevserver-klient-applet</artifactId>
									<outputDirectory>${project.build.directory}/${project.build.finalName}
									</outputDirectory>
									<destFileName>StartBrevklientApplet.jar</destFileName>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<packagingExcludes>WEB-INF/lib/*.jar</packagingExcludes>
					<archive>
						<manifest>
							<classpathPrefix>lib/</classpathPrefix>
							<addClasspath>true</addClasspath>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
					</archive>
					<exportManifestToDir>${basedir}/META-INF</exportManifestToDir>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>