//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.17 at 10:47:39 PM CEST 
//


package no.nav.tjenester.brevogarkiv.dokumentbehandling;

import jakarta.activation.DataHandler;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlMimeType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ferdigstillDokumentRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ferdigstillDokumentRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="brevreferanse" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kvitteringskoe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="malpakke" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nyttDokument" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="brukerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="redDokument" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="pdfDokument" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ferdigstillDokumentRequest", propOrder = {
    "brevreferanse",
    "systemId",
    "token",
    "kvitteringskoe",
    "malpakke",
    "nyttDokument",
    "brukerId",
    "redDokument",
    "pdfDokument"
})
public class FerdigstillDokumentRequest {

    @XmlElement(required = true)
    protected String brevreferanse;
    @XmlElement(required = true)
    protected String systemId;
    @XmlElement(required = true)
    protected String token;
    protected String kvitteringskoe;
    protected String malpakke;
    protected boolean nyttDokument;
    @XmlElement(required = true)
    protected String brukerId;
    @XmlElement(required = true)
    @XmlMimeType("application/octet-stream")
    protected DataHandler redDokument;
    @XmlElement(required = true)
    @XmlMimeType("application/octet-stream")
    protected DataHandler pdfDokument;

    /**
     * Gets the value of the brevreferanse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrevreferanse() {
        return brevreferanse;
    }

    /**
     * Sets the value of the brevreferanse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrevreferanse(String value) {
        this.brevreferanse = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the kvitteringskoe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKvitteringskoe() {
        return kvitteringskoe;
    }

    /**
     * Sets the value of the kvitteringskoe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKvitteringskoe(String value) {
        this.kvitteringskoe = value;
    }

    /**
     * Gets the value of the malpakke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMalpakke() {
        return malpakke;
    }

    /**
     * Sets the value of the malpakke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMalpakke(String value) {
        this.malpakke = value;
    }

    /**
     * Gets the value of the nyttDokument property.
     * 
     */
    public boolean isNyttDokument() {
        return nyttDokument;
    }

    /**
     * Sets the value of the nyttDokument property.
     * 
     */
    public void setNyttDokument(boolean value) {
        this.nyttDokument = value;
    }

    /**
     * Gets the value of the brukerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrukerId() {
        return brukerId;
    }

    /**
     * Sets the value of the brukerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrukerId(String value) {
        this.brukerId = value;
    }

    /**
     * Gets the value of the redDokument property.
     * 
     * @return
     *     possible object is
     *     {@link DataHandler }
     *     
     */
    public DataHandler getRedDokument() {
        return redDokument;
    }

    /**
     * Sets the value of the redDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataHandler }
     *     
     */
    public void setRedDokument(DataHandler value) {
        this.redDokument = value;
    }

    /**
     * Gets the value of the pdfDokument property.
     * 
     * @return
     *     possible object is
     *     {@link DataHandler }
     *     
     */
    public DataHandler getPdfDokument() {
        return pdfDokument;
    }

    /**
     * Sets the value of the pdfDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataHandler }
     *     
     */
    public void setPdfDokument(DataHandler value) {
        this.pdfDokument = value;
    }

}
