//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.17 at 10:47:39 PM CEST 
//


package no.nav.tjenester.brevogarkiv.dokumentbehandling;

import jakarta.activation.DataHandler;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlMimeType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hentDokumentResponse2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hentDokumentResponse2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="knappStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dokumentData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hentDokumentResponse2", propOrder = {
    "knappStatus",
    "dokumentData"
})
public class HentDokumentResponse2 {

    @XmlElement(required = true)
    protected String knappStatus;
    @XmlElement(required = true)
    @XmlMimeType("application/octet-stream")
    protected DataHandler dokumentData;

    /**
     * Gets the value of the knappStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKnappStatus() {
        return knappStatus;
    }

    /**
     * Sets the value of the knappStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKnappStatus(String value) {
        this.knappStatus = value;
    }

    /**
     * Gets the value of the dokumentData property.
     * 
     * @return
     *     possible object is
     *     {@link DataHandler }
     *     
     */
    public DataHandler getDokumentData() {
        return dokumentData;
    }

    /**
     * Sets the value of the dokumentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataHandler }
     *     
     */
    public void setDokumentData(DataHandler value) {
        this.dokumentData = value;
    }

}
