//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.17 at 10:47:39 PM CEST 
//


package no.nav.tjenester.brevogarkiv.dokumentbehandling;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.tjenester.brevogarkiv.dokumentbehandling package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AvbrytDokumentRequest_QNAME = new QName("http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", "avbrytDokumentRequest");
    private final static QName _HentDokumentResponse2_QNAME = new QName("http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", "hentDokumentResponse2");
    private final static QName _FerdigstillDokumentRequest_QNAME = new QName("http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", "ferdigstillDokumentRequest");
    private final static QName _FerdigstillDokumentResponse_QNAME = new QName("http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", "ferdigstillDokumentResponse");
    private final static QName _PingResponse_QNAME = new QName("http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", "pingResponse");
    private final static QName _LagreDokumentResponse_QNAME = new QName("http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", "lagreDokumentResponse");
    private final static QName _AvbrytDokumentResponse_QNAME = new QName("http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", "avbrytDokumentResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.tjenester.brevogarkiv.dokumentbehandling
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AvbrytDokumentRequest }
     *
     */
    public AvbrytDokumentRequest createAvbrytDokumentRequest() {
        return new AvbrytDokumentRequest();
    }

    /**
     * Create an instance of {@link HentDokumentResponse2 }
     *
     */
    public HentDokumentResponse2 createHentDokumentResponse2() {
        return new HentDokumentResponse2();
    }

    /**
     * Create an instance of {@link FerdigstillDokumentRequest }
     *
     */
    public FerdigstillDokumentRequest createFerdigstillDokumentRequest() {
        return new FerdigstillDokumentRequest();
    }

    /**
     * Create an instance of {@link HentDokument }
     *
     */
    public HentDokument createHentDokument() {
        return new HentDokument();
    }

    /**
     * Create an instance of {@link HentDokumentRequest }
     *
     */
    public HentDokumentRequest createHentDokumentRequest() {
        return new HentDokumentRequest();
    }

    /**
     * Create an instance of {@link HentDokumentResponse }
     *
     */
    public HentDokumentResponse createHentDokumentResponse() {
        return new HentDokumentResponse();
    }

    /**
     * Create an instance of {@link FerdigstillDokument }
     *
     */
    public FerdigstillDokument createFerdigstillDokument() {
        return new FerdigstillDokument();
    }

    /**
     * Create an instance of {@link Ping }
     *
     */
    public Ping createPing() {
        return new Ping();
    }

    /**
     * Create an instance of {@link PingRequest }
     *
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link LagreDokument }
     *
     */
    public LagreDokument createLagreDokument() {
        return new LagreDokument();
    }

    /**
     * Create an instance of {@link LagreDokumentRequest }
     *
     */
    public LagreDokumentRequest createLagreDokumentRequest() {
        return new LagreDokumentRequest();
    }

    /**
     * Create an instance of {@link AvbrytDokument }
     *
     */
    public AvbrytDokument createAvbrytDokument() {
        return new AvbrytDokument();
    }

    /**
     * Create an instance of {@link Base64Binary }
     *
     */
    public Base64Binary createBase64Binary() {
        return new Base64Binary();
    }

    /**
     * Create an instance of {@link HexBinary }
     *
     */
    public HexBinary createHexBinary() {
        return new HexBinary();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvbrytDokumentRequest }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AvbrytDokumentRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", name = "avbrytDokumentRequest")
    public JAXBElement<AvbrytDokumentRequest> createAvbrytDokumentRequest(AvbrytDokumentRequest value) {
        return new JAXBElement<AvbrytDokumentRequest>(_AvbrytDokumentRequest_QNAME, AvbrytDokumentRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HentDokumentResponse2 }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link HentDokumentResponse2 }{@code >}
     */
    @XmlElementDecl(namespace = "http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", name = "hentDokumentResponse2")
    public JAXBElement<HentDokumentResponse2> createHentDokumentResponse2(HentDokumentResponse2 value) {
        return new JAXBElement<HentDokumentResponse2>(_HentDokumentResponse2_QNAME, HentDokumentResponse2.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FerdigstillDokumentRequest }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FerdigstillDokumentRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", name = "ferdigstillDokumentRequest")
    public JAXBElement<FerdigstillDokumentRequest> createFerdigstillDokumentRequest(FerdigstillDokumentRequest value) {
        return new JAXBElement<FerdigstillDokumentRequest>(_FerdigstillDokumentRequest_QNAME, FerdigstillDokumentRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", name = "ferdigstillDokumentResponse")
    public JAXBElement<Object> createFerdigstillDokumentResponse(Object value) {
        return new JAXBElement<Object>(_FerdigstillDokumentResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", name = "pingResponse")
    public JAXBElement<Object> createPingResponse(Object value) {
        return new JAXBElement<Object>(_PingResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", name = "lagreDokumentResponse")
    public JAXBElement<Object> createLagreDokumentResponse(Object value) {
        return new JAXBElement<Object>(_LagreDokumentResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://dokumentbehandling.brevogarkiv.tjenester.nav.no/", name = "avbrytDokumentResponse")
    public JAXBElement<Object> createAvbrytDokumentResponse(Object value) {
        return new JAXBElement<Object>(_AvbrytDokumentResponse_QNAME, Object.class, null, value);
    }

}
