<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>brevserver</artifactId>
		<groupId>no.nav.brevserver</groupId>
		<version>10.2.1-SNAPSHOT</version>
	</parent>
	<artifactId>brevserver-consumer-joark-ejb</artifactId>
	<name>${project.artifactId}</name>
	<version>10.2.1-SNAPSHOT</version>
	<packaging>ejb</packaging>

	<dependencies>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-server-common-java</artifactId>
		</dependency>
		<dependency>
			<groupId>no.stelvio</groupId>
			<artifactId>stelvio-consumer-java</artifactId>
		</dependency>
		<dependency>
			<groupId>no.stelvio</groupId>
			<artifactId>stelvio-common-java</artifactId>
		</dependency>
		<dependency>
			<groupId>net.sf.dozer</groupId>
			<artifactId>dozer</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.ejb</groupId>
			<artifactId>ejb</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>jsr250-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>

		<dependency>
			<groupId>no.nav.tjenester</groupId>
			<artifactId>nav-journal-tjenestespesifikasjon</artifactId>
			<classifier>jaxws</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester</groupId>
			<artifactId>nav-journalbehandling-tjenestespesifikasjon</artifactId>
			<classifier>jaxws</classifier>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<type>pom</type>
			<exclusions>
				<exclusion>
					<groupId>com.sun.xml.ws</groupId>
					<artifactId>release-documentation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.xml.ws</groupId>
					<artifactId>samples</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Test dependencies -->
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-config</artifactId>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
					<archive>
						<manifest>
							<classpathPrefix>lib/</classpathPrefix>
							<addClasspath>true</addClasspath>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>Unpack wsdls</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<configuration>
							<includeClassifiers>jaxws</includeClassifiers>
							<outputDirectory>${project.build.directory}/classes/META-INF/</outputDirectory>
							<includes>**/*.wsdl,**/*.xsd</includes>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>