kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: brevserver-nais
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SPRING_DATASOURCE_URL
      value: {{ SPRING_DATASOURCE_URL }}
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: MOTTAK_ARKIV_QUEUENAME
      value: {{ MOTTAK_ARKIV_QUEUENAME }}
    - name: MOTTAK_ARKIV_PE_QUEUENAME
      value: {{ MOTTAK_ARKIV_PE_QUEUENAME }}
    - name: DIALOGUE_ONLINE_QUEUENAME
      value: {{ DIALOGUE_ONLINE_QUEUENAME }}
    - name: DIALOGUE_ONLINE_PE_QUEUENAME
      value: {{ DIALOGUE_ONLINE_PE_QUEUENAME }}
    - name: ONLINEBREV_QUEUENAME
      value: {{ ONLINEBREV_QUEUENAME }}
    - name: ONLINEBREV_PE_QUEUENAME
      value: {{ ONLINEBREV_PE_QUEUENAME }}
    - name: MOTTAK_ONLINE_QUEUENAME
      value: {{ MOTTAK_ONLINE_QUEUENAME }}
    - name: MOTTAK_ONLINE_PE_QUEUENAME
      value: {{ MOTTAK_ONLINE_PE_QUEUENAME }}
    - name: BREV_REPLY_PE_QUEUENAME
      value: {{ BREV_REPLY_PE_QUEUENAME }}
    - name: DEADLETTER_QUEUENAME
      value: {{ DEADLETTER_QUEUENAME }}
    - name: DEADLETTER_PE_QUEUENAME
      value: {{ DEADLETTER_PE_QUEUENAME }}
    - name: FAGARKIV_ENDPOINTS_JOURNAL
      value: {{ FAGARKIV_ENDPOINTS_JOURNAL }}
    - name: FAGARKIV_ENDPOINTS_JOURNALBEHANDLING
      value: {{ FAGARKIV_ENDPOINTS_JOURNALBEHANDLING }}
    - name: FAGARKIV_PROXY_HOST
      value: {{ FAGARKIV_PROXY_HOST }}
    - name: FAGARKIV_PROXY_PORT
      value: "{{ FAGARKIV_PROXY_PORT }}"
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
    - name: BREVSERVER_SERVER
      value: {{ BREVSERVER_SERVER }}
    - name: BREVSERVERCHANNEL_NAME
      value: {{ BREVSERVERCHANNEL_NAME }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
        - {{ this }}
    {{/each}}
  liveness:
    path: brevweb/isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: brevweb/isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 3072Mi
    requests:
      memory: 1920Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVBREVSERVER }}
        mountPath: /var/run/secrets/nais.io/srvbrevserver
      - kvPath: {{ BREVSERVER_VAULT }}
        mountPath: /var/run/secrets/nais.io/vault