kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  env:
    - name: SPRING_DATASOURCE_URL
      value: {{ SPRING_DATASOURCE_URL }}
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: MQGATEWAY01_CHANNEL_NAME
      value: {{ MQGATEWAY01_CHANNEL_NAME }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: MQGATEWAY01_CHANNEL_ENABLETLS
      value: "{{ MQGATEWAY01_CHANNEL_ENABLETLS }}"
    - name: MOTTAK_ARKIV_QUEUENAME
      value: {{ MOTTAK_ARKIV_QUEUENAME }}
    - name: MOTTAK_ARKIV_PE_QUEUENAME
      value: {{ MOTTAK_ARKIV_PE_QUEUENAME }}
    - name: DIALOGUE_ONLINE_QUEUENAME
      value: {{ DIALOGUE_ONLINE_QUEUENAME }}
    - name: DIALOGUE_ONLINE_PE_QUEUENAME
      value: {{ DIALOGUE_ONLINE_PE_QUEUENAME }}
    - name: ONLINEBREV_QUEUENAME
      value: {{ ONLINEBREV_QUEUENAME }}
    - name: ONLINEBREV_PE_QUEUENAME
      value: {{ ONLINEBREV_PE_QUEUENAME }}
    - name: MOTTAK_ONLINE_QUEUENAME
      value: {{ MOTTAK_ONLINE_QUEUENAME }}
    - name: MOTTAK_ONLINE_LINUX_QUEUENAME
      value: {{ MOTTAK_ONLINE_LINUX_QUEUENAME }}
    - name: MOTTAK_ONLINE_PE_QUEUENAME
      value: {{ MOTTAK_ONLINE_PE_QUEUENAME }}
    - name: MOTTAK_ONLINE_PE_LINUX_QUEUENAME
      value: {{ MOTTAK_ONLINE_PE_LINUX_QUEUENAME }}
    - name: MOTTAK_ARKIV_PE_LINUX_QUEUENAME
      value: {{ MOTTAK_ARKIV_PE_LINUX_QUEUENAME }}
    - name: BREV_REPLY_PE_QUEUENAME
      value: {{ BREV_REPLY_PE_QUEUENAME }}
    - name: DEADLETTER_QUEUENAME
      value: {{ DEADLETTER_QUEUENAME }}
    - name: DEADLETTER_PE_QUEUENAME
      value: {{ DEADLETTER_PE_QUEUENAME }}
    - name: MOTTAK_ARKIV_BQ_QUEUENAME
      value: {{ MOTTAK_ARKIV_BQ_QUEUENAME }}
    - name: MOTTAK_ARKIV_PE_BQ_QUEUENAME
      value: {{ MOTTAK_ARKIV_PE_BQ_QUEUENAME }}
    - name: BESTILL_BREV_BQ_QUEUENAME
      value: {{ BESTILL_BREV_BQ_QUEUENAME }}
    - name: BESTILL_BREV_PE_BQ_QUEUENAME
      value: {{ BESTILL_BREV_PE_BQ_QUEUENAME }}
    - name: FAGARKIV_ENDPOINTS_JOURNAL
      value: {{ FAGARKIV_ENDPOINTS_JOURNAL }}
    - name: FAGARKIV_ENDPOINTS_JOURNALBEHANDLING
      value: {{ FAGARKIV_ENDPOINTS_JOURNALBEHANDLING }}
    - name: FAGARKIV_PROXY_HOST
      value: {{ FAGARKIV_PROXY_HOST }}
    - name: FAGARKIV_PROXY_PORT
      value: "{{ FAGARKIV_PROXY_PORT }}"
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
    - name: APPD_NAME
      value: {{ APPD_NAME }}
    - name: BREVSERVERPROPERTIES_LOGGXML
      value: "{{ BREVSERVERPROPERTIES_LOGGXML }}"
    - name: BREVSERVERPROPERTIES_DATABASE_POOLSIZE
      value: "{{ BREVSERVERPROPERTIES_DATABASE_POOLSIZE }}"
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
        - {{ this }}
    {{/each}}
  liveness:
    path: brevweb/actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: brevweb/actuator/prometheus
  readiness:
    path: brevweb/actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 4096Mi
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  {{#if AZURE_IAC_RULES}}
  accessPolicy:
    inbound:
      rules:
      {{#each AZURE_IAC_RULES}}
        - application: {{ app }}
          namespace: {{ namespace }}
          cluster: {{ cluster }}
      {{/each}}
  {{/if}}
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVBREVSERVER }}
        mountPath: /var/run/secrets/nais.io/srvbrevserver
      - kvPath: {{ BREVSERVER_VAULT }}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: {{ BREVSERVER_DS }}
        mountPath: /var/run/secrets/nais.io/brevserverDS
      - kvPath: {{ APPDYNAMICS }}
        mountPath: "/var/run/secrets/nais.io/appdynamics"
      - kvPath: {{ BREVSERVERCERT }}
        mountPath: /var/run/secrets/nais.io/certificate