# database
spring.datasource.driver-class-name=oracle.jdbc.pool.OracleDataSource
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.hibernate.ddl-auto=validate
spring.transaction.default-timeout=300s
# flyway
spring.flyway.enabled=true
spring.flyway.table=schema_version
spring.flyway.out-of-order=false
spring.flyway.baseline-on-migrate=true
logging.config=classpath:logback-spring.xml

com.ibm.mq.cfg.AMQ_DISABLE_CLIENT_AMS=TRUE
server.servlet.context-path=/brevweb
BrevserverServiceBean.knappstatus.default=7
BrevserverServiceBean.knappstatus.BI01.BI01P11=15
BrevserverServiceBean.knappstatus.BI01.BI01P18=15
BrevserverServiceBean.knappstatus.BI01.BI01X01=15
BrevserverServiceBean.knappstatus.BI01.BI01X02=15
BrevserverServiceBean.knappstatus.PE_IY_03_156=15
BrevserverServiceBean.knappstatus.PE_UT_04_101=15
BrevserverServiceBean.knappstatus.PE_UT_04_102=15
BrevserverServiceBean.knappstatus.PE_UT_04_104=15
BrevserverServiceBean.knappstatus.PE_IY_05_300=15
BrevserverServiceBean.knappstatus.GE_IY_03_156=15

spring.main.allow-bean-definition-overriding=true
spring.main.banner_mode=off
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# actuators
management.endpoints.web.exposure.include=prometheus,health
# actuator - health
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.health.diskspace.enabled=false
# actuator - metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.enable.http.client.requests=false