# database
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DB2390Dialect
spring.jpa.properties.hibernate.generate_statistics=false
spring.transaction.default-timeout=300s
