<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>brevserver</artifactId>
		<groupId>no.nav.brevserver</groupId>
		<version>10.2.1-SNAPSHOT</version>
	</parent>
	<artifactId>brevserver-j2ee</artifactId>
	<name>${project.artifactId}</name>
	<packaging>ear</packaging>
	<version>10.2.1-SNAPSHOT</version>

	<dependencies>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-server-business-ejb</artifactId>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-consumer-joark-ejb</artifactId>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>no.nav.brevserver</groupId>
			<artifactId>brevserver-provider-ws</artifactId>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester.brevogarkiv</groupId>
			<artifactId>dokumentbehandling-tjenestespesifikasjon</artifactId>
			<classifier>jaxws</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester.brevogarkiv</groupId>
			<artifactId>loggmottak-tjenestespesifikasjon</artifactId>
			<classifier>jaxws</classifier>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Delete the files in the lib folder -->
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<configuration>
					<filesets>
						<fileset>
							<directory>${basedir}/lib/</directory>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
			<!-- Create the EAR file -->
			<plugin>
				<artifactId>maven-ear-plugin</artifactId>
				<configuration>
					<version>5</version>
					<defaultJavaBundleDir>lib/</defaultJavaBundleDir>
					<displayName>${project.artifactId}-${project.version}</displayName>
					<archive>
						<manifest>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
					</archive>
					<security>
						<security-role>
							<role-name>JoarkWsClient</role-name>
						</security-role>
					</security>
					<modules>
						<ejbModule>
							<groupId>no.nav.brevserver</groupId>
							<artifactId>brevserver-server-business-ejb</artifactId>
						</ejbModule>
						<ejbModule>
							<groupId>no.nav.brevserver</groupId>
							<artifactId>brevserver-consumer-joark-ejb</artifactId>
							<bundleFileName>brevserver-consumer-joark-ejb.jar</bundleFileName>
						</ejbModule>
						<webModule>
							<groupId>no.nav.brevserver</groupId>
							<artifactId>brevserver-provider-ws</artifactId>
							<context-root>${web.context.root}</context-root>
							<bundleFileName>brevserver-provider-ws.war</bundleFileName>
						</webModule>
					</modules>
				</configuration>
			</plugin>
			<!-- Copy dependencies to the lib folder -->
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<overWriteSnapshots>true</overWriteSnapshots>
							<overWriteReleases>true</overWriteReleases>
							<outputDirectory>lib/</outputDirectory>
							<includeScope>runtime</includeScope>
							<excludeTypes>war</excludeTypes>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>